pkg/process/finders/storage.go, test/e2e/base/base-compose.yml, test/e2e/cases/process/istio/e2e.yaml
When a process has multiple entities, such as in the Kubernetes detector, the process may belong to MESH and K8S_SERVICE.
Currently, the rover only matches the **first** process ID to process. When profiling the process, it will not match the process.
=> Fix process id analyze error when same process bind to multiple entities

pkg/tools/profiling/go_library.go
For now, the elf file must contain symbol selection, but some elf files (such as `libc.so`) only have dynamic symbols. We can't ignore them.
=> Improve symbol analyzer

.github/workflows/rover.yaml, .gitignore, CHANGES.md, Makefile, dist/LICENSE, dist/LICENSE.tpl, docker/Dockerfile.build, pkg/profiling/task/offcpu/runner.go, pkg/profiling/task/oncpu/runner.go, pkg/tools/btf/check.go, pkg/tools/btf/ebpf.go, pkg/tools/operator/distribution.go, pkg/tools/operator/uname.go, scripts/build/base.mk, scripts/build/bash/btfgen.sh, scripts/build/btf.mk, scripts/release/create_bin_release.sh
Follow Blog: https://kinvolk.io/blog/2022/03/btfgen-one-step-closer-to-truly-portable-ebpf-programs/
I see it could help users running the eBPF program with CO-RE on the old kernel(without recompile kernel), It's pretty cool. So we could add it.
=> Introduce the BTFhub module

CHANGES.md, pkg/tools/host/file.go
The problem occurs when the rover is running in a docker-in-docker environment(like `kind`) because its privileged mode reads information from the docker, not from the host. 
So when the rover reads the process information in the container, it must be exactly according to "ROVER_HOST_MAPPING".
=> Fixed reading process paths incorrect when running as a container

CHANGES.md, pkg/profiling/task/network/analyze/layer7/protocols/http1/sampling.go
…ausing the rover to restart
```
panic: interface conversion: interface {} is *http1.URISampling, not *base.NetworkSamplingRule
goroutine 108 [running]:
github.com/apache/skywalking-rover/pkg/profiling/task/network/analyze/layer7/protocols/http1.(*SamplingConfig).findMatchesRule(0xc001744120, {0xc0151f6584, 0xc})
/src/pkg/profiling/task/network/analyze/layer7/protocols/http1/sampling.go:189 +0xeb
github.com/apache/skywalking-rover/pkg/profiling/task/network/analyze/layer7/protocols/http1.(*Sampler).AppendMetrics(0xc0003aad98, 0xc001744120, 0x31e9359, 0xc014f2c100, 0xc00189a480, {0x1ba2e30?, 0xc0152a2900}, {0x1ba2dd0?, 0xc0183d88a0})
/src/pkg/profiling/task/network/analyze/layer7/protocols/http1/sampling.go:78 +0x1a5
github.com/apache/skywalking-rover/pkg/profiling/task/network/analyze/laye …
```
=> Fixed submitting multiple network profiling tasks with the same uri causing the rover to restart

CHANGES.md, bpf/include/api.h, bpf/include/goid.h, bpf/include/symbol_offsets.h, bpf/profiling/continuous/go_tls.c, bpf/profiling/network/go_tls.c, bpf/profiling/offcpu.h, pkg/profiling/continuous/checker/bpf/network/ssl.go, pkg/profiling/task/network/ssl.go, pkg/tools/ssl/gotls.go
Inspired by pixie, we can no longer use `runtime.casgstatus` to get `goid`. Instead, get it directly from the local storage of the current thread.
=> Improve the performance when getting `goid` in eBPF

test/e2e/cases/profiling/task/network/golang/service.go
```ioutil.readAll()``` is deprecated in Go 1.19.
https://pkg.go.dev/io/ioutil@go1.19#example-ReadAll
=> replace deprecated function

.github/workflows/publish-docker.yaml, scripts/build/bash/btfgen.sh
Following https://github.com/apache/skywalking-rover/actions/runs/5255995428/jobs/9509747351, the temporary build directory needs to be deleted when building the docker image on GHA to reduce the disk space.
=> Remove tmp path when building docker

.github/workflows/publish-docker.yaml
Following https://github.com/apache/skywalking-rover/actions/runs/6594862069, I encountered a space issue during the docker image push. Therefore, this PR attempts to clear space before pushing the image.
=> Resolve the insufficient space error while pushing Docker images with GitHub Action

pkg/process/finders/kubernetes/finder.go
If the service name already contains the cluster name, then ignore to adding them into the service name.
=> Support overwire the cluster name by user defined

docs/en/setup/overview.md, docs/menu.yml
I polished some words in the docs.
=> Polish docs

CHANGES.md, bpf/accesslog/syscalls/transfer.h, bpf/include/socket_data.h, bpf/profiling/network/args.h, bpf/profiling/network/netmonitor.c, bpf/profiling/network/sock_stats.h, docker/Dockerfile.base
Following CI error: https://github.com/mrproliu/skywalking-rover/actions/runs/9347730187/job/25725345091?pr=22
Currently, the llvm package dependency has removed the download for version `13.x`, so we upgraded the llvm version to the latest version `18` to prevent errors when downloading dependency packages during future compilations.
=> Upgrade LLVM to `18` for eBPF code compile

CHANGES.md, bpf/accesslog/l24/read_l3.c, bpf/include/list.h
When I execute `make generate` on my system with Linux headers version 6.2 or higher, I got the following error:
```
skywalking-rover/bpf/include/list.h:65:8: error: redefinition of 'bpf_list_head'
65 | struct bpf_list_head {
|        ^
/usr/include/linux/bpf.h:7136:8: note: previous definition is here
7136 | struct bpf_list_head {
|        ^
```
I followed @mrproliu advice to add a prefix for bpf_list_head struct, it generate go file successfuly, I tested it in my local, it works well, Thanks for your help @mrproliu .
=> Fix errors when compiling C source files into eBPF bytecode.

CHANGES.md, pkg/accesslog/collector/l24.go
Following https://github.com/apache/skywalking/issues/12324 and https://github.com/torvalds/linux/blob/v4.18/net/ipv4/ip_input.c, It appears that `ip_list_rcv` does not exist in older kernel versions.
=> Fixed `ip_list_rcv` probe is not exist in older linux kernel

CHANGES.md, pkg/accesslog/common/connection.go
Sometimes rover execution is terminated because multiple goroutines operate on the same map. This PR will fix this problem.
=> Fix concurrent map operation in the access log module

CHANGES.md, docker/Dockerfile.base, pkg/accesslog/common/connection.go, pkg/accesslog/forwarder/close.go, pkg/accesslog/runner.go
When the system runs for a long time due to excessive invalid Active Connections in BPF, it becomes unable to write new connection information. This PR introduces the interval cleanup policy to remove invalid Active Connections from BPF.
=> Fix some connections not called close syscall, causing unnecessary memory usage

CHANGES.md, pkg/process/finders/kubernetes/container.go, pkg/process/finders/kubernetes/finder.go
When I'm trying to deploy the skywalking rover in the OpenShift, the processes cannot be detected. Because the OpenShift uses the `CRI-O` container runtime as default. So, in this PR, I made the rover support to detect the `CRI-O` based process to fix the issue which cannot found any process.
=> Add detect process from `CRI-O` container in Kubernetes.

CHANGES.md, bpf/accesslog/accesslog.c, bpf/accesslog/ambient/ztunnel.c, bpf/accesslog/ambient/ztunnel.h, go.mod, go.sum, pkg/accesslog/collector/ztunnel.go, pkg/accesslog/common/connection.go, pkg/accesslog/events/ztunnel.go, pkg/tools/elf/elf.go, scripts/build/bash/btfgen.sh
In the Istio ambient mode, it uses ztunnel to load balance the request. 
Therefore, when the downstream sends a request to the upstream in Istio ambient mode, the rover can only know the remote service IP in the downstream request. After monitoring the ztunnel method, the rover can detect the real upstream IP address.
=> Support monitoring ztunnel to adapt istio ambient mode

CHANGES.md, configs/rover_configs.yaml, pkg/accesslog/collector/connect.go, pkg/accesslog/common/config.go
If the monitoring process frequently **uses short connections for communication**, it may generate a large amount of connection information. Therefore, in this PR, Rover supports reading new connection information using multiple goroutines.
=> Separate multiple process for reading connection information in the access log module

pkg/profiling/task/oncpu/runner.go
When I was reading the code, I discovered this small mistake. Although it may not have any actual impact, I still believe it's necessary to correct it.
=> Fix the bad command parameter of bpf2go

pkg/profiling/continuous/checker/common/http_checker.go, pkg/profiling/continuous/checker/network_error_rate.go, pkg/profiling/continuous/checker/network_response_time.go
These generic functions and generic structures are unnecessary and only make the code harder to read, so these generics have been removed.
=> Remove unnecessary generic parameters

bpf/accesslog/l24/read_l2.c, bpf/accesslog/l24/write_l2.c, bpf/accesslog/l24/write_l4.c, bpf/accesslog/process/process.c, bpf/accesslog/syscalls/close.c, bpf/accesslog/syscalls/connect.c, bpf/accesslog/syscalls/transfer.c, bpf/include/api.h
As mentioned in this issue (https://github.com/apache/skywalking/discussions/12779), modification were made to the input parameters of tracepoint programs to ensure compatibility with scenarios where kernel parameter sizes vary, preventing potential errors. The detailed modification infomation can be found at https://github.com/apache/skywalking/discussions/12779#discussioncomment-11322309.
=> Fix context structs parameters for tracepoint programs

CHANGES.md, bpf/include/socket_data.h, bpf/include/socket_opts.h
As described in the [Fix the unaligned memory accesses for upload_socket_data_buf in skywalking-rover](https://github.com/apache/skywalking/issues/12830), Fix the unaligned memory accesses.
=> Fix the unaligned memory accesses for upload_socket_data_buf

CHANGES.md, bpf/accesslog/syscalls/transfer.h, bpf/accesslog/tls/go_tls.c, bpf/accesslog/tls/go_tls.h
Currently, since the first socket detail is sent based on protocol content during HTTPS parsing, the first socket detail data is treated as a non-protocol kernel event and cannot be associated with the protocol. 
This PR addresses this issue.
=> Fix missing the first socket detail event in HTTPS protocol

CHANGES.md, configs/rover_configs.yaml, pkg/accesslog/collector/connection.go, pkg/accesslog/collector/protocols/queue.go, pkg/accesslog/common/config.go, pkg/profiling/continuous/checker/bpf/network/network.go, pkg/profiling/task/network/analyze/layer7/events.go, pkg/tools/btf/linker.go, pkg/tools/btf/queue.go
When the business system traffic is high, the Rover will convert its traffic between kernel mode and user mode through BPF Queue. Previously, there was only a single goroutine to receive, parse, and then send it to the routing analysis goroutine. This caused the parsing process to require waiting until the next receive. 
Therefore, it now supports multiple goroutines to receive and parse events in the queue from being discarded due to waiting for parsing during high traffic.
This is similar to the concept of boss and worker groups in Netty, where boss and worker groups are two separate thread pools. The boss is responsible for receiving connections, while the worker handles processing them. In Rover, the boss (parse) group receives events, and the worker (analyze) group processes events.
=> Support parallel parsing protocol data in the access log module

.github/workflows/rover.yaml, CHANGES.md, bpf/accesslog/common/connection.h, bpf/accesslog/syscalls/transfer.h, bpf/include/queue.h, bpf/include/socket_data.h, pkg/accesslog/bpf/loader.go, pkg/accesslog/collector/protocols/queue.go, pkg/profiling/continuous/checker/bpf/network/network.go, pkg/profiling/task/network/analyze/layer7/events.go, pkg/profiling/task/network/analyze/layer7/protocols/http1/reader/reader.go, pkg/profiling/task/network/bpf/bpf.go, pkg/profiling/task/offcpu/runner.go, pkg/tools/btf/ebpf.go, pkg/tools/btf/linker.go, pkg/tools/btf/queue.go, pkg/tools/buffer/buffer.go
In Linux version 5.8, a ring buffer was introduced to replace the original perf buffer array to enhance transmission performance between kernel space and user space. 
Therefore, the access log module can optimize execution efficiency based on whether the system provides a ring buffer data structure.
=> Introduce ringbuf queue in access log module

pkg/accesslog/collector/connection.go, pkg/tools/ip/conntrack.go
In the ambient mesh 1.23, It will still using iptables to send request to `127.0.0.1:15001`. Cause the ztunnel match failure.
=> Adapt ambient mesh 1.23 iptables mode
