configs/rover_configs.yaml
go.mod
go.sum
pkg/process/finders/storage.go
pkg/process/finders/vm/process.go

* Update the default Layer name as `OS_LINUX`
* Update the process identity type.
* Adopt the latest gRPC eBPF Process protocol.

Adapt the gRPC process protocol

---

.github/workflows/rover.yaml
configs/rover_configs.yaml
go.mod
go.sum
pkg/process/api/process.go
pkg/process/finders/storage.go
pkg/process/finders/vm/config.go
pkg/process/finders/vm/finder.go

Follow https://github.com/apache/skywalking/issues/8833
We need to disable the E2E temporarily because it breaks the previous version of the CLI and OAP sides.
After the OAP side is finished, I would create another PR to activate the E2E again.

Add Label to the process

---

pkg/process/finders/kubernetes/finder.go
pkg/process/finders/kubernetes/process.go
pkg/process/finders/scanner/finder.go
pkg/process/finders/scanner/process.go
test/e2e/cases/process/agent_sensor/golang/expected/process.yml
test/e2e/cases/process/istio/expected/process.yml
test/e2e/cases/process/istio/expected/service-instance.yml
test/e2e/cases/process/istio/expected/service.yml

Upload all processes matching the process discovery module.
Whether the process can be profiled and uploaded only as property.

Add could be profiling properties in to process

---

pkg/tools/process.go
pkg/tools/profiling/api.go
pkg/tools/profiling/kernel.go

Fix Bugs:
- kernel symbols could not be resolved.
- File offset adapt exception.

Fix bug and add debug logs for find symbols

---

.github/workflows/rover.yaml
configs/rover_configs.yaml
docker/Dockerfile.build
docs/en/setup/configuration/process_discovery/overview.md
go.mod
go.sum
pkg/process/api/process.go
pkg/process/config.go
pkg/process/finders/base/finder.go
pkg/process/finders/base/tool.go
pkg/process/finders/kubernetes/finder.go
pkg/process/finders/kubernetes/registry.go
pkg/process/finders/manager.go
pkg/process/finders/scanner/finder.go
pkg/process/finders/storage.go
pkg/process/module.go

1. Add `properties_report_period` config.
2. Update the process protocol. 
3. Simplify the sync process function.

Update the process protocol

---

CHANGES.md
bpf/profiling/oncpu.c
bpf/profiling/oncpu.h
pkg/profiling/task/offcpu/runner.go
pkg/profiling/task/oncpu/runner.go

Follow https://man7.org/linux/man-pages/man2/perf_event_open.2.html The description of the `sample_period, sample_freq`, we need to change the ON_CPU to frequency sampling mode.

Update to using frequency mode to `ON_CPU` Profiling.

---

bpf/profiling/network/args.h
bpf/profiling/network/netmonitor.c
bpf/profiling/network/protocol_analyze.h
bpf/profiling/network/sock_stats.h
go.mod
go.sum
pkg/process/api/process.go
pkg/process/finders/base/process.go
pkg/process/finders/base/template.go
pkg/process/finders/context.go
pkg/process/finders/kubernetes/process.go
pkg/process/finders/scanner/process.go
pkg/process/finders/storage.go
pkg/profiling/task/network/analyzer.go
pkg/profiling/task/network/context.go
pkg/profiling/task/network/delegate.go
pkg/profiling/task/network/linker.go
pkg/profiling/task/network/metrics.go
pkg/profiling/task/network/runner.go
pkg/profiling/task/network/tcpresolver.go

* Optimized eBPF event handler
* Optimize the connection closing event handle process
* Fix traffic direction identification errors

Enhance the network profiling

---

CHANGES.md
configs/rover_configs.yaml
docs/en/setup/configuration/logger.md
docs/en/setup/overview.md
docs/menu.yml
internal/cmd/start.go
pkg/boot/module.go
pkg/boot/register.go
pkg/logger/module.go
pkg/logger/settings.go

We cannot change the logging level in the docker/Kubernetes environment, so I have updated the logger to a configurable module to make it easier to change the configuration in the environment variable or file.

Let the logger as a configurable module

---

CHANGES.md
bpf/profiling/network/args.h
bpf/profiling/network/netmonitor.c
bpf/profiling/network/openssl.c
bpf/profiling/network/openssl.h
bpf/profiling/network/sock_stats.h
pkg/profiling/task/network/analyzer.go
pkg/profiling/task/network/context.go
pkg/profiling/task/network/enums.go
pkg/profiling/task/network/linker.go
pkg/profiling/task/network/metrics.go
pkg/profiling/task/network/runner.go
pkg/profiling/task/network/ssl.go
pkg/tools/process.go
pkg/tools/profiling/go_library.go

* Analyze protocol when the data is in the connection
* Support for analyzing protocols that use the OpenSSL library program
* Add the `protocol` and `is_ssl` labels to the metrics when uploading to the backend

Support OpenSSL library and add protocol and IsSSL labels in metrics

---

CHANGES.md
bpf/profiling/network/args.h
bpf/profiling/network/go_tls.c
bpf/profiling/network/go_tls.h
bpf/profiling/network/netmonitor.c
docs/en/setup/configuration/profiling.md
go.mod
go.sum
pkg/profiling/task/network/enums.go
pkg/profiling/task/network/linker.go
pkg/profiling/task/network/ssl.go
pkg/tools/elf/abi.go
pkg/tools/elf/dwarf.go
pkg/tools/elf/dwarf_init.go
pkg/tools/elf/elf.go
pkg/tools/elf/enums.go
pkg/tools/elf/function.go
pkg/tools/elf/structure.go
pkg/tools/profiling/api.go
pkg/tools/profiling/go_library.go
pkg/tools/profiling/kernel.go

The feature is used for the Golang application to analyze the data, which application uses TLS/SSL to encrypt or decrypt data. 
I will provide E2E to verify the mainstream language with HTTPS.

Support analyze the data from GoTLS

---

docs/en/setup/configuration/profiling.md
pkg/profiling/task/network/analyzer.go
pkg/profiling/task/network/context.go
pkg/profiling/task/network/metrics.go
pkg/profiling/task/network/runner.go

* Add Network profiling documentation
* Update the unit of the socket write RTT as microsecond

Add Network profiling documentation

---

.asf.yaml
README.md

The project has wider tech scope, I reword the description to make features more clear.
@mrproliu Please check docs, whether we need adjustments too.

Reword project description.

---

pkg/tools/host/time.go

Before this PR, we only can get the `second` of the Linux boot time. The timestamp is not very accurate when we get the attached event's start/end time, Because the `nanosecond` is missing.
This PR enhances the boot time to get the `nanosecond` of the boot time.

Enhance the boot time for getting the nanosecond

---

README.md
docs/en/concepts-and-designs/overview.md

I think you should update 
1. https://skywalking.apache.org/docs/skywalking-rover/next/en/concepts-and-designs/project_structue/ to the latest project structure
2. Add the Linux version support matrix here, https://skywalking.apache.org/docs/skywalking-rover/next/en/setup/overview/

Update feature lists

---

CHANGES.md
bpf/profiling/network/protocol_analyzer.h
pkg/profiling/task/network/analyze/layer7/protocols/http1/reader/reader.go

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

Fix HTTP method name in protocol analyzer

---

pkg/profiling/task/network/ssl.go

Also update err msg as we don't check fix version only.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

chore: correct var name

---

CHANGES.md
bpf/profiling/network/args.h
bpf/profiling/network/netmonitor.c
bpf/profiling/network/sock_stats.h
bpf/profiling/network/socket.h
bpf/profiling/network/socket_detail.c
bpf/profiling/network/socket_detail.h
docs/en/setup/configuration/profiling.md
pkg/profiling/task/network/analyze/base/enums.go
pkg/profiling/task/network/analyze/layer7/events.go
pkg/profiling/task/network/analyze/layer7/protocols/base/analyzer.go
pkg/profiling/task/network/analyze/layer7/protocols/base/buffer.go
pkg/profiling/task/network/analyze/layer7/protocols/base/buffer_test.go
pkg/profiling/task/network/analyze/layer7/protocols/base/events.go
pkg/profiling/task/network/analyze/layer7/protocols/http1/metrics.go
pkg/profiling/task/network/analyze/layer7/protocols/protocols.go
pkg/profiling/task/network/analyze/layer7/queue.go
pkg/profiling/task/network/runner.go
pkg/tools/host/network.go

Including the following summary of the event:
1. Network interface information
2. RTT metrics
3. Package Count/Size
4. Syscall function name(write, read, etc.)

Add the syscall level event to the trace

---

CHANGES.md
bpf/profiling/network/args.h
bpf/profiling/network/sock_stats.h
bpf/profiling/network/socket_detail.h
docker/Dockerfile.build
pkg/profiling/task/network/analyze/base/connection.go
pkg/profiling/task/network/analyze/base/events.go
pkg/profiling/task/network/analyze/layer4/listener.go
pkg/profiling/task/network/analyze/layer7/events.go
pkg/profiling/task/network/analyze/layer7/listener.go
pkg/profiling/task/network/analyze/layer7/protocols/base/analyzer.go
pkg/profiling/task/network/analyze/layer7/protocols/base/buffer.go
pkg/profiling/task/network/analyze/layer7/protocols/base/events.go
pkg/profiling/task/network/analyze/layer7/protocols/http1/reader/reader.go
pkg/profiling/task/network/analyze/layer7/protocols/protocols.go

1. Optimized the data structure in the BPF program, reducing the amount of data sent from the kernel to the user-space program.
2. Fixed the issue of memory growth caused by the socket detail data not being deleted for a long time.

Optimization and Bug Fix for BPF and Socket Detail Data

---

.github/workflows/rover.yaml
CHANGES.md
bpf/include/api.h
bpf/include/goid.h
bpf/include/symbol_offsets.h
bpf/include/syscall_reading.h
bpf/profiling/continuous/network.c
bpf/profiling/network/netmonitor.c
docker/Dockerfile.base
docker/Dockerfile.build
pkg/profiling/continuous/checker/bpf/network/network.go
pkg/profiling/task/network/analyze/layer7/protocols/base/buffer.go
pkg/profiling/task/network/bpf/bpf.go
pkg/profiling/task/offcpu/runner.go
pkg/tools/btf/linker.go
pkg/tools/elf/abi.go
scripts/build/base.mk
scripts/build/btf.mk
scripts/build/build.mk
scripts/build/docker.mk
scripts/build/generate.mk

Support pushing multiple architecture docker images to the registry. For now, the GHA hasn't `arm64` instance, so I checked in the local machine and it works well.

Support build multiple architecture docker image: `x86_64`, `arm64`

---

bpf/profiling/offcpu.c

Replace the way to get tgid and pid.

replace the way to get tgid and pid

---

CHANGES.md
scripts/build/docker.mk

See also the discussions https://github.com/apache/skywalking/discussions/11438

chore: add the latest image tag into the build command

---

docs/en/setup/deployment/kubernetes/readme.md

Fix a spelling mistake about 'kubectl'

Fix a spelling mistake about 'kubectl'

---

CHANGES.md
bpf/accesslog/common/connection.h
bpf/include/api.h
bpf/include/socket.h
pkg/accesslog/runner.go

In some scenarios, the address information in the connection may not be obtained through existing probes. The enhanced feature supports obtaining the current operating socket information through the current task itself.

Enhance get connection address strategy in access log module.

---

CHANGES.md
docker/Dockerfile.build
docker/Dockerfile.debug
scripts/build/build.mk

As described in  [Feature Improve the compilation of skywalking-rover](https://github.com/apache/skywalking/issues/12789)  , improve the build of skywalking-rover.

Improve the build of skywalking-rover
